# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule MmnApi.Model.BroadcastSummary do
  @moduledoc """
  A short representation of a broadcast object
  """

  @derive [Poison.Encoder]
  defstruct [
    :"broadcastCode",
    :"broadcastId",
    :"title",
    :"description",
    :"emergency",
    :"paramsMetadata"
  ]
end

defimpl Poison.Decoder, for: MmnApi.Model.BroadcastSummary do
  import MmnApi.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"paramsMetadata", :list, MmnApi.Model.ParamsMetadata, options)
  end
end

