# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule MmnApi.Model.Broadcast do
  @moduledoc """
  A broadcast object
  """

  @derive [Poison.Encoder]
  defstruct [
    :"title",
    :"description",
    :"recipients",
    :"mediums",
    :"options",
    :"conferenceNumber",
    :"subject",
    :"textMessageLong",
    :"textMessageShort",
    :"audioURI",
    :"paramsMetadata",
    :"saved",
    :"broadcastId",
    :"createdTime",
    :"broadcastCode"
  ]
end

defimpl Poison.Decoder, for: MmnApi.Model.Broadcast do
  import MmnApi.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"recipients", :list, MmnApi.Model.Recipient, options)
    |> deserialize(:"audioURI", :struct, MmnApi.Model.HttpUri, options)
    |> deserialize(:"paramsMetadata", :list, MmnApi.Model.ParamsMetadata, options)
  end
end

