# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule MmnApi.Model.ConferenceStatus do
  @moduledoc """
  a conference status object
  """

  @derive [Poison.Encoder]
  defstruct [
    :"roomNumber",
    :"participants"
  ]
end

defimpl Poison.Decoder, for: MmnApi.Model.ConferenceStatus do
  import MmnApi.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"participants", :list, MmnApi.Model.ConferenceParticipant, options)
  end
end

