# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule MmnApi.Model.Contact do
  @moduledoc """
  A contact object
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"title",
    :"uniqueId",
    :"firstName",
    :"lastName",
    :"contactMethods",
    :"notes"
  ]
end

defimpl Poison.Decoder, for: MmnApi.Model.Contact do
  import MmnApi.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"contactMethods", :list, MmnApi.Model.ContactMethod, options)
  end
end

