# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule MmnApi.Model.Endpoint do
  @moduledoc """
  an endpoint object
  """

  @derive [Poison.Encoder]
  defstruct [
    :"data",
    :"title",
    :"id"
  ]
end

defimpl Poison.Decoder, for: MmnApi.Model.Endpoint do
  def decode(value, _options) do
    value
  end
end

