# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule MmnApi.Model.Group do
  @moduledoc """
  a group object
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"title",
    :"type",
    :"members",
    :"description",
    :"data"
  ]
end

defimpl Poison.Decoder, for: MmnApi.Model.Group do
  import MmnApi.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"members", :list, MmnApi.Model.Endpoint, options)
  end
end

