# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule MmnApi.Model.HttpUri do
  @moduledoc """
  an HTTP URI object, e.g. an audio file. Main field is &#39;httpURI&#39;. Other parameters contain instructions how to retrieve the remote object.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"httpURI",
    :"remote",
    :"method",
    :"contentType",
    :"contentLang",
    :"scheme",
    :"username",
    :"password"
  ]
end

defimpl Poison.Decoder, for: MmnApi.Model.HttpUri do
  def decode(value, _options) do
    value
  end
end

