# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule MmnApi.Model.MoSmsMessage do
  @moduledoc """
  Mobile Originated SMS Message
  """

  @derive [Poison.Encoder]
  defstruct [
    :"smsFrom",
    :"operation",
    :"message",
    :"route",
    :"version",
    :"smsDate",
    :"routerTimestamp",
    :"network",
    :"smsId",
    :"smsTo",
    :"sendSmsResponse"
  ]
end

defimpl Poison.Decoder, for: MmnApi.Model.MoSmsMessage do
  def decode(value, _options) do
    value
  end
end

