# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule MmnApi.Model.ParamsMetadata do
  @moduledoc """
  Metadata for a broadcast parameter. Needed only if default value or instructions are not empty.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"deflt",
    :"instr"
  ]
end

defimpl Poison.Decoder, for: MmnApi.Model.ParamsMetadata do
  def decode(value, _options) do
    value
  end
end

