# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule MmnApi.Model.ReportEventListenerRegistrationRequest do
  @moduledoc """
  A report event listener object
  """

  @derive [Poison.Encoder]
  defstruct [
    :"reportId",
    :"callbackURL",
    :"configurationData",
    :"secretKey",
    :"type"
  ]
end

defimpl Poison.Decoder, for: MmnApi.Model.ReportEventListenerRegistrationRequest do
  def decode(value, _options) do
    value
  end
end

