# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule MmnApi.Model.ReportRecipientStatus do
  @moduledoc """
  Recipient status in a broadcast
  """

  @derive [Poison.Encoder]
  defstruct [
    :"eventTime",
    :"eventType",
    :"broadcastType",
    :"ownerId",
    :"reportId",
    :"detail",
    :"endpointId",
    :"endData",
    :"endType",
    :"ownerSecondary",
    :"ownerPrimary"
  ]
end

defimpl Poison.Decoder, for: MmnApi.Model.ReportRecipientStatus do
  def decode(value, _options) do
    value
  end
end

