# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule MmnApi.Model.Report do
  @moduledoc """
  A summary report of the broadcast
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"submitTime",
    :"startedTime",
    :"endedTime",
    :"broadcastId",
    :"broadcastName",
    :"state",
    :"sender",
    :"total",
    :"completed",
    :"confirmed",
    :"delivered",
    :"undelivered",
    :"failed",
    :"division"
  ]
end

defimpl Poison.Decoder, for: MmnApi.Model.Report do
  def decode(value, _options) do
    value
  end
end

