# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule MmnApi.Model.SendBroadcastActionParameterBody do
  @moduledoc """
  The optional broadcast parameters and/or recipientLocation URI
  """

  @derive [Poison.Encoder]
  defstruct [
    :"recipientLocation",
    :"params"
  ]
end

defimpl Poison.Decoder, for: MmnApi.Model.SendBroadcastActionParameterBody do
  import MmnApi.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"params", :map, MmnApi.Model.Object, options)
  end
end

