# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule MmnApi.Model.SimpleMessage do
  @moduledoc """
  A simple message sent using BC&#39;s notification capabilities without creating a broadcast
  """

  @derive [Poison.Encoder]
  defstruct [
    :"address",
    :"medium",
    :"content"
  ]
end

defimpl Poison.Decoder, for: MmnApi.Model.SimpleMessage do
  def decode(value, _options) do
    value
  end
end

