# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule MmnApi.Model.Version do
  @moduledoc """
  MMN version and build information object
  """

  @derive [Poison.Encoder]
  defstruct [
    :"version",
    :"revision",
    :"buildTimestamp",
    :"platform",
    :"instanceID"
  ]
end

defimpl Poison.Decoder, for: MmnApi.Model.Version do
  def decode(value, _options) do
    value
  end
end

