# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule MmnApi.Api.Conference do
  @moduledoc """
  API calls for all endpoints tagged `Conference`.
  """

  alias MmnApi.Connection
  import MmnApi.RequestBuilder


  @doc """
  Cancel a conference room by number
  Action KILL will disconnect all opt-in conference participants. Admin privileges are required for this call.

  ## Parameters

  - connection (MmnApi.Connection): Connection to server
  - room_number (Integer): conference room number
  - action (String): conference action (only KILL is supported)
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %{}} on success
  {:error, info} on failure
  """
  @spec cancel_conference(Tesla.Env.client, Integer.t, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def cancel_conference(connection, room_number, action, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/conference/#{room_number}")
    |> add_param(:query, :"action", action)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(false)
  end

  @doc """
  Get list of active opt-in conferences
  Returns a list of voice conferences that are currently in progress. Admin privileges are required for this call.

  ## Parameters

  - connection (MmnApi.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, [%ConferenceStatus{}, ...]} on success
  {:error, info} on failure
  """
  @spec get_conferences(Tesla.Env.client, keyword()) :: {:ok, list(MmnApi.Model.ConferenceStatus.t)} | {:error, Tesla.Env.t}
  def get_conferences(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/conference")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode([%MmnApi.Model.ConferenceStatus{}])
  end
end
